#
# Makefile for development
#


PY_SRC_PATH=../compbio

RASMUS_SRC_FILES = \
	__init__.py \
	hmm.py \
	intervals.py \
	linked_list.py \
	plotting.py \
        tablelib.py \
        timer.py \
        treelib.py \
	testing.py \
	textdraw.py \
	sets.py \
        stats.py \
        svg.py \
        util.py \

COMPBIO_SRC_FILES = \
	__init__.py \
	alignlib.py \
	arglib.py \
	birthdeath.py \
	coal.py \
	fasta.py \
	phylo.py \
	seqlib.py \
	vis/__init__.py \
	vis/argvis.py

# copy subset of python modules for packaging with argweaver
includedep:
	mkdir -p argweaver/deps
	touch argweaver/deps/__init__.py
	./setup/cp-deps.py $(PY_SRC_PATH)/rasmus argweaver/deps/rasmus $(RASMUS_SRC_FILES)
	./setup/cp-deps.py $(PY_SRC_PATH)/compbio argweaver/deps/compbio $(COMPBIO_SRC_FILES)
